http:
  routers:
    traefik:
      rule: (Host(`localhost`) || Host(`traefik.remote.bitsonline.nl`)) && (PathPrefix(`/api`) || Host(`traefik.lan.bitsonline.nl`)) && (PathPrefix(`/api`)|| PathPrefix(`/dashboard`))
      entryPoints:
        - traefik
      service: api@internal
      middlewares:
        - service-chain@file
      tls:
        certResolver: letsencrypt
        domains:
          - main: remote.bitsonline.nl
            sans:
              - '*.remote.bitsonline.nl'
        options: tls-modern
    ping:
      rule: "(Host(`localhost`) || Host(`traefik.remote.bitsonline.nl`)) && PathPrefix(`/ping`)"
      entryPoints:
        - ping
      service: "ping@internal"
      tls:
        certResolver: letsencrypt
        domains:
          - main: "remote.bitsonline.nl"
            sans:
              - "*.remote.bitsonline.nl"

