http:
  routers:
    traefik:
      rule: (Host(`traefik.lan.bitsonline.nl`)) && (PathPrefix(`/api`)) || PathPrefix(`/dashboard`)
      entryPoints:
        - traefik
      service: api@internal
      middlewares:
        - service-chain@file
      tls: {}
    ping:
      rule: "Host(`traefik.lan.bitsonline.nl`) && PathPrefix(`/ping`)"
      entryPoints:
        - ping
      service: "ping@internal"
      tls: {}
      middlewares:
        - service-chain@file
