services:
  caddy:
    image: ghcr.io/buildplan/caddy-plus:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    env_file:
      - .env
    environment:
      - CADDY_ADMIN=unix//run/caddy/caddy-admin.sock
      - DOCKER_HOST=tcp://socket-proxy:2375
      - TZ=Europe/Amsterdam
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CADDY_DOCKER_CADDYFILE_PATH=/config/Caddyfile
      - CROWDSEC_API_KEY=${CROWDSEC_API_KEY}
      - CADDY_DOCKER_PROCESS_CADDYFILE=true
      - CADDY_INGRESS_NETWORKS=proxy
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - OAUTH2_PROXY_PROVIDER=oidc
      - OAUTH2_PROXY_OIDC_ISSUER_URL=https://auth.indehoven.com/application/o/caddy/
      - OAUTH2_PROXY_CLIENT_ID=${OAUTH2_PROXY_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${OAUTH2_PROXY_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}
      - OAUTH2_PROXY_WHITELIST_DOMAINS=.indehoven.com
      - OAUTH2_PROXY_COOKIE_DOMAINS=.indehoven.com
      - OAUTH2_PROXY_EMAIL_DOMAINS=*
      - OAUTH2_PROXY_INSECURE_OIDC_ALLOW_UNVERIFIED_EMAIL=true
      - OAUTH2_PROXY_SKIP_PROVIDER_BUTTON=true
    networks:
      - proxy
      - backend
    expose:
      - "4180"
    volumes:
      - /dockerdata/caddy_plus/config:/config
      - /dockerdata/caddy_plus/data:/data
      - caddy_admin:/run
      - /dockerdata/caddy_plus/data/www:/data/www
      - caddy_logs:/var/log/caddy
    aliases: 
      - proxy
      - oauth2-proxy

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    container_name: crowdsec
    env_file:
      - .env
    environment:
      - CROWDSEC_LAPI_LISTEN_URI=0.0.0.0:8080
      - CROWDSEC_API_KEY=${CROWDSEC_API_KEY}
      - TZ=Europe/Amsterdam
      - DOCKER_HOST=tcp://socket-proxy:2375
      - COLLECTIONS=crowdsecurity/caddy crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules
      - CROWDSEC_BOUNCER_KEY=${CROWDSEC_BOUNCER_KEY}
      - CROWDSEC_USER=${CROWDSEC_USER}
      - CROWDSEC_PASSWORD=${CROWDSEC_PASSWORD}
      - CROWDSEC_LAPI_URL=http://localhost:8080
    networks:
      - proxy
      - backend
    aliases: 
      - appsec
    volumes:
      - /dockerdata/caddy_plus/crowdsec-db:/var/lib/crowdsec/data
      - /dockerdata/caddy_plus/crowdsec-config/acquis.yaml:/etc/crowdsec/acquis.yaml
      - caddy_logs:/var/log/caddy
      - /dockerdata/caddy_plus/crowdsec-config:/etc/crowdsec

networks:
  proxy:
    external: true
  backend:
    external: true

volumes:
  caddy_data:
  crowdsec-db:
  caddy_logs:
    external: true
