services:
  aliasvault:
    image: ghcr.io/aliasvault/aliasvault:latest
    container_name: aliasvault
    hostname: aliasvault
    restart: unless-stopped

    ports:
      - "1080:80"
      - "1443:443"
      - "25:25"
      - "587:587"

    volumes:
      - ./data/database:/database
      - ./data/logs:/logs
      - ./data/secrets:/secrets
      - ./data/certificates:/certificates
      - caddy_logs:/var/log/caddy

    environment:
      HOSTNAME: "localhost"
      PUBLIC_REGISTRATION_ENABLED: "true"
      IP_LOGGING_ENABLED: "true"
      FORCE_HTTPS_REDIRECT: "false"
      SUPPORT_EMAIL: ""
      PRIVATE_EMAIL_DOMAINS: ""
      HIDDEN_PRIVATE_EMAIL_DOMAINS: ""
      TZ: "Europe/Amsterdam"
      DOCKER_HOST: "tcp://socket-proxy:2375"
    
    networks:
      - proxy
      - "internal network"

networks:
  proxy:
    external: true
  "internal network":
    external: true

volumes:
  database:
  logs:
  secrets:
  certificates:
  caddy_logs:
    external: true


