services:
  dns-server:
    container_name: dns
    image: technitium/dns-server:latest
    network_mode: "host"
    volumes:
      - ./config:/etc/dns
      - caddy_logs:/var/log/caddy
    env_file:
      - .env
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65535
volumes:
  caddy_logs:
    external: true