services:
  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:latest
    container_name: zerobyte
    hostname: zerobyte
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    ports:
      - 4096:4096
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      - TZ=Europe/Amsterdam
      - DOCKER_HOST=tcp://socket-proxy:2375
      - BASE_URL=https://zerobyte.indehoven.com # URL you will use to access Zerobyte
      - APP_SECRET=c02c1fa849244e433b6fa945296bacd0081e86013f5d32ebc7135794296473bf
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/lib/zerobyte:/var/lib/zerobyte
      - caddy_logs:/var/log/caddy
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  caddy_logs:
    external: true