services:
  postgresql:
    container_name: authentik-postgresql
    env_file:
      - .env
    environment:
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__NAME: ${PG_DB:-authentik}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER:-authentik}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
      TZ: "Europe/Amsterdam"
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
      - CMD-SHELL
      - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    volumes:
    - authentik_database:/var/lib/postgresql/data
    networks:
      - backend
  authentik_redis:
    container_name: authentik-redis
    env_file:
      - .env
    environment:
      TZ: "Europe/Amsterdam"
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - authentik_redis:/var/lib/redis/data
    ports:
      - 6380:6379
    networks:
      - backend
  server:
    container_name: authentik-server
    command: server
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      TZ: "Europe/Amsterdam"
      DOCKER_HOST: "tcp://socket-proxy:2375"
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2026.5.2}
    ports:
      - 9001:9000
      - 9002:9443
    restart: unless-stopped
    shm_size: 512mb
    volumes:
      - ./data:/data
      - ./data/custom-templates:/templates
      - caddy_logs:/var/log/caddy
    networks:
      - proxy
      - backend
  worker:
    container_name: authentik-worker
    command: worker
    depends_on:
      postgresql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DOCKER_HOST: "tcp://socket-proxy:2375"
      TZ: "Europe/Amsterdam"
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2026.5.2}
    restart: unless-stopped
    shm_size: 512mb
    user: root
    volumes:
      - ./data:/data
      - ./data/certs:/certs
      - ./data/custom-templates:/templates
    networks:
      - backend
  outpost-proxy:
    container_name: authentik-outpost-proxy
    command: proxy
    image: ghcr.io/goauthentik/proxy
    networks:
       - proxy
       - backend
    restart: unless-stopped
    shm_size: 512mb
    user: root
    ports:
       - 9003:9000
       - 9004:9443
    env_file:
       - .env
    environment:
       AUTHENTIK_HOST: https://outpost-proxy.indehoven.com
       AUTHENTIK_INSECURE: "false"
       AUTHENTIK_TOKEN: token-generated-by-authentik      
       DOCKER_HOST: "tcp://socket-proxy:2375"
       TZ: "Europe/Amsterdam"
       AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:?secret key required}
networks:
  proxy:
    external: true
  backend:
    external: true
volumes:
  authentik_database:
    external: true
  caddy_logs:
    external: true
  authentik_redis:
    external: true