global:
  checkNewVersion: true
  sendAnonymousUsage: false
api:
  dashboard: true
  insecure: true
  debug: true
log:
  level: "DEBUG"
metrics:
  prometheus:
    entrypoint: "metrics"
ping:
  entryPoint: ping
  manualRouting: true
entryPoints:
  traefik:
    address: ":8080"
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      trustedIPs:
      - "192.168.2.0/24"
      - "172.16.0.0/12"
      - "127.0.0.0/8"
      - "10.0.0.0/8"
  metrics:
    address: ":6060/tcp"
  ping:
    address: ":81/tcp"
  socket:
    address: ":2375/tcp"
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      trustedIPs:
      - "192.168.2.0/24"
      - "172.16.0.0/12"
      - "127.0.0.0/8"
      - "10.0.0.0/8"
  dns-tcp-proxy:
    address: ":538/tcp"
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      trustedIPs:
      - "192.168.2.0/24"
      - "172.16.0.0/12"
      - "127.0.0.0/8"
      - "10.0.0.0/8"
  dns-udp-proxy:
    address: ":538/udp"
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      trustedIPs:
      - "192.168.2.0/24"
      - "172.16.0.0/12"
      - "127.0.0.0/8"
      - "10.0.0.0/8"
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true
    proxyProtocol:
    - "192.168.2.0/24"
    - "172.16.0.0/12"
    - "127.0.0.0/8"
    - "10.0.0.0/8"
    http:
      aliasHeadersStrategy: delete
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
      - 192.168.2.0/24
      - 172.16.0.0/12
      - 127.0.0.0/8
      - 10.0.0.0/8
    proxyProtocol:
      trustedIPs:
      - 192.168.2.0/24
      - 172.16.0.0/12
      - 127.0.0.0/8
      - 10.0.0.0/8
    http:
      tls:
        certResolver: cloudflare
        options: tls-modern@file
      middlewares:
      - secure-chain@file
    asDefault: true

    http3: {}
providers:
  docker:
    endpoint: tcp:///socket-proxy:2375
    defaultRule: Host(`{{ index .Labels 
      "com.docker.compose.service"}}.lan.bitsonline.nl`)
    exposedByDefault: false
    network: proxy
  file:
    directory: /dynamic
  swarm:
    endpoint: tcp:///socket-proxy:2375
    defaultRule: Host(`{{ index .Labels 
      "com.docker.compose.service"}}.swarm.bitsonline.nl`)
    exposedByDefault: false
    watch: true
    network: traefik_swarm_proxy

certificatesResolvers:
  cloudflare:
    acme:
      email: "dennisbitsonline@gmail.com"
      storage: "/certs/acme.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory" # prod (default)
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      dnsChallenge:
        provider: cloudflare
        disablePropagationCheck: true # uncomment this if you have issues pulling certificates through cloudflare, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.
        delayBeforeCheck: 60s # uncomment along with disablePropagationCheck if needed to ensure the TXT record is ready before verification is attempted 
        resolvers:
        - 1.1.1.1:53
        - 1.0.0.1:53
  local-tls:
    acme:
      email: "local-tls@8it5.nl"
      storage: "/certs/local-tls.json"
      tlsChallenge: {}
  letsencrypt:
    acme:
      httpChallenge:
        entryPoint: web
      email: "local-http@8it5.nl"
      storage: "/certs/local-http.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"

serversTransport:
  insecureSkipVerify: true
experimental:
  plugins:
    crowdsec-bouncer-traefik-plugin:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.8.0-alpha
    badger:
      moduleName: github.com/fosrl/badger
      version: v1.7.0