global:
  checkNewVersion: true
  sendAnonymousUsage: false
api:
  dashboard: true
  insecure: true
  debug: true
log:
  filePath: "/logs/traefik.log"
  format: json
  level: DEBUG
  maxSize: 10
  maxBackups: 3
  maxAge: 1
  compress: true
accessLog:
  filePath: "/logs/traefik-access.log"
  # JSON format
  format: json
  # Filter on status codes, retry attempts and minimal duration
  filters:
    statusCodes:
    - '200'
    - 300-302
    retryAttempts: true
    minDuration: "10ms"
  fields:
    # Keep all the fields by default
    defaultMode: keep
    names:
      # Drop the Field ClientUserName
      ClientUsername: drop
    headers:
      # Keep all the headers by default
      defaultMode: keep
      names:
        # Redact the User-Agent header value
        User-Agent: redact
        # Drop the Authorization header value
        Authorization: drop
    queryParameters:
      # Drop all query parameters
      defaultMode: drop
metrics:
  prometheus:
    entrypoint: "metrics"
ping:
  entryPoint: "ping"
  manualRouting: true
  terminatingStatusCode: 204
entryPoints:
  traefik:
    address: ":8080"
  metrics:
    address: ":6060"
  ping:
    address: ":8082"
  socket:
    address: ":2375/tcp"
  dns-tcp-proxy:
    address: ":538/tcp"
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      trustedIPs:
      - "192.168.2.0/24"
      - "172.16.0.0/12"
      - "127.0.0.0/8"
      - "10.0.0.0/8"
  dns-udp-proxy:
    address: ":538/udp"
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      trustedIPs:
      - "192.168.2.0/24"
      - "172.16.0.0/12"
      - "127.0.0.0/8"
      - "10.0.0.0/8"
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true
    proxyProtocol:
    - "192.168.2.0/24"
    - "172.16.0.0/12"
    - "127.0.0.0/8"
    - "10.0.0.0/8"
    http:
      aliasHeadersStrategy: keep
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
      - 192.168.2.0/24
      - 172.16.0.0/12
      - 127.0.0.0/8
      - 10.0.0.0/8
    proxyProtocol:
      trustedIPs:
      - 192.168.2.0/24
      - 172.16.0.0/12
      - 127.0.0.0/8
      - 10.0.0.0/8
    http:
      tls:
        certResolver: cloudflare
        options: tls-modern@file
    asDefault: true
providers:
  docker:
    endpoint: tcp:///socket-proxy:2375
    defaultRule: Host(`{{ index .Labels 
      "com.docker.compose.service"}}.app.bitsonline.nl`)
    exposedByDefault: false
    network: proxy
  file:
    directory: /dynamic
certificatesResolvers:
  cloudflare:
    acme:
      email: "dennisbitsonline@gmail.com"
      storage: "/certs/acme.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory" # prod (default)
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      dnsChallenge:
        provider: cloudflare
        disablePropagationCheck: true # uncomment this if you have issues pulling certificates through cloudflare, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.
        delayBeforeCheck: 60s # uncomment along with disablePropagationCheck if needed to ensure the TXT record is ready before verification is attempted 
        resolvers:
        - 1.1.1.1:53
        - 1.0.0.1:53
  local-tls:
    acme:
      email: "local-tls@8it5.nl"
      storage: "/certs/local-tls.json"
      tlsChallenge: {}
  letsencrypt:
    acme:
      httpChallenge:
        entryPoint: web
      email: "local-http@8it5.nl"
      storage: "/certs/local-http.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"

serversTransport:
  insecureSkipVerify: true
experimental:
  plugins:
    bouncer:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.7.1
    badger:
      moduleName: github.com/fosrl/badger
      version: v1.7.0