global:
  checkNewVersion: true
  sendAnonymousUsage: false
api:
  dashboard: true
  insecure: true
  debug: true
log:
  level: "DEBUG"
metrics:
  prometheus:
   entrypoint: "metrics"
ping:
  entryPoint: ping
  manualRouting: true
entryPoints:
  technitium:
    address: ":53443/tcp"
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      trustedIPs:
        - "192.168.2.0/24"
        - "172.16.0.0/12"
        - "127.0.0.0/8"
  traefik:
    address: ":8080"
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      trustedIPs:
        - "192.168.2.0/24"
        - "172.16.0.0/12"
        - "127.0.0.0/8"
  metrics:
    address: ":6060/tcp"
  ping:
    address: ":81/tcp"
  tunnel:
    address: ":2112/tcp"
  wireguard:
    address: ":51820/udp"
  client-tunnel:
    address: ":21820/udp"
  socket:
    address: ":2375/tcp"
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      trustedIPs:
        - "192.168.2.0/24"
        - "172.16.0.0/12"
        - "127.0.0.0/8"
  dns-tcp-proxy:
    address: ":538/tcp"
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      trustedIPs:
        - "192.168.2.0/24"
        - "172.16.0.0/12"
        - "127.0.0.0/8"
  dns-udp-proxy:
    address: ":538/udp"
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      trustedIPs:
        - "192.168.2.0/24"
        - "172.16.0.0/12"
        - "127.0.0.0/8"
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true
    proxyProtocol:
        - "192.168.2.0/24"
        - "172.16.0.0/12"
        - "127.0.0.0/8"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      trustedIPs:
        - "192.168.2.0/24"
        - "172.16.0.0/12"
        - "127.0.0.0/8"
    http:
      tls: {}
    asDefault: true

providers:
  docker:
    endpoint: tcp:///socket-proxy:2375
    defaultRule: Host(`{{ index .Labels 
      "com.docker.compose.service"}}.lan.bitsonline.nl`) || Host(`{{ index 
      .Labels "com.docker.compose.service"}}.bitsonline.nl`) || Host(`{{ index 
      .Labels "com.docker.compose.service"}}.8it5.nl`) || Host(`{{ index .Labels
      "com.docker.compose.service"}}.indehoven.com`) || Host(`{{ index .Labels 
      "com.docker.compose.service"}}.remote.8it5.nl`) || Host(`{{ index .Labels 
      "com.docker.compose.service"}}.remote.bitsonline.nl`)
    exposedByDefault: false
    network: proxy
    watch: true
  file:
    directory: /dynamic
    watch: true
certificatesResolvers:
  cloudflare:
    acme:
      email: dennisbitsonline@gmail.com
      storage: /certs/acme.json
      caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      dnsChallenge:
        provider: cloudflare
        disablePropagationCheck: false # uncomment this if you have issues pulling certificates through cloudflare, By setting this flag to true disables the need to wait for the propagation of the TXT record to all authoritative name servers.
        delayBeforeCheck: 60s # uncomment along with disablePropagationCheck if needed to ensure the TXT record is ready before verification is attempted 
        resolvers:
          - 1.1.1.1:53
          - 1.0.0.1:53
  local-tls:
    acme:
      email: local-tls@8it5.nl
      storage: /certs/local-tls.json
      tlsChallenge: {}
  local-http:
    acme:
      email: local-http@8it5.nl
      storage: /certs/local-http.json
      httpChallenge:
        entrypoint: "web"
serversTransport:
  insecureSkipVerify: true
experimental:
  plugins:
    crowdsec-bouncer-traefik-plugin:
      moduleName: github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      version: v1.8.0-alpha
    badger:
      moduleName: github.com/fosrl/badger
      version: v1.7.0