# Dozzle - Real-time Docker Log Viewer
services:
  dozzle-agent:
    image: amir20/dozzle:latest
    container_name: dozzle
    hostname: dozzle
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 5s
      retries: 5
      start_period: 5s
      start_interval: 5s
    volumes:
        - caddy_logs:/var/log/caddy
    ports:
      - 8181:8080
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_FILTER: "status=running"
      DOZZLE_HOSTNAME: "dozzle.indehoven.com"
      TZ: "Europe/Amsterdam"
      DOCKER_HOST: "tcp://socket-proxy:2375"
    networks:
      - proxy
      - "internal network"
networks:
  proxy:
    external: true
  "internal network":
    external: true

volumes:
  caddy_logs:
    external: true

